### ISSUE TITLE
Place order does not work

### ISSUE THREAD

**Issue by andreiashu** [mondeja/bittrex_v2#1]
Hi thank you for this repo. I tried to use the place_order functionality but I'm either doing something wrong or there's a bug somewhere. Unfortunately I don't have the v2 API docs (does anyone have them apart from bittrex themselves?) so don't really know what's going on

```python
from bittrex_v2 import Bittrex
# API keys 
b = Bittrex(api_key="KEY", api_secret="SECRET")

uuid = b.place_order("BUY", "BTC-OMG", 18, 0.00025100, "LIMIT", "GOOD_TIL_CANCELLED")
print('UUID {}'.format(uuid))
```
Then run it like
```bash
$ python3 myscript.py
UUID {'success': False, 'message': 'There was a problem processing your request.  If this problem persists, please email support@bittrex.com with this error id - xxxx-xxxx-xxx-xxxx', 'result': None}
```

Update: forgot to mention that I double checked that the API key that I am using has the LIMIT/MARKET permissions set already. Read access also is enabled and I was able to test it by fetching the currently open orders that I have for a market (BTC-OMG).

Update2: it's also worth noting that I have enough BTC in my balance that should allow this order to be placed (ie. when I place an order via the UI with these same parameters it does work)

**Comment by ghost** [comment]
Docs: https://github.com/ericsomdahl/python-bittrex/issues/35#issuecomment-326191279

**Comment by c0bra-dev** [comment]
just specify, as parameter `conditionType="NONE"`
in your example
`uuid = b.place_order("BUY", "BTC-OMG", 18, 0.00025100, "LIMIT", "GOOD_TIL_CANCELLED",conditionType="NONE")`

Should do the job

**Comment by mondeja** [comment]
Until bittrex does not release the documentation we can't know how to use conditions for placing orders.

**Comment by DocHak** [comment]
OMG, I didn't realize I had to put "conditionType="NONE"".  

So this code (on line 387 of bittrex.py):
if not conditionType:
            conditionType = "CONDITION_NONE"

Should be:
if not conditionType:
            conditionType = "NONE"

**Comment by mondeja** [comment]
Thanks @DocHak, it's done.
